name = "ace-worker"
main = "src/worker.js"
compatibility_date = "2024-04-05"

[vars]
# We set secrets via command line, so leave this empty

# ADD THIS SECTION:
[[r2_buckets]]
binding = "ACE_BUCKET"           # <--- We will use this name in the code
bucket_name = "ace-athlete-data" # <--- Your actual R2 bucket name
preview_bucket_name = "ace-athlete-data" # (Optional: Needed if you run 'wrangler dev' with real data)

[observability]
enabled = false

[[d1_databases]]
binding = "DB"
database_name = "ace"
database_id = "446762e4-3bb7-4522-8225-a573c7d8e34e"